apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "wb.fullname" . }}
  labels:
    app: {{ template "wb.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
{{- define "wb.inlineconfigs" }}
nginx.conf: |-
  user  nginx;
  worker_processes  1;

  load_module /usr/lib/nginx/modules/ngx_http_brotli_filter_module.so;

  error_log  /var/log/nginx/error.log warn;
  pid        /var/run/nginx.pid;

  events {
      worker_connections 1024;
  }

  http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;

      log_format main '$remote_addr - $upstream_cache_status $remote_user [$time_local] '
                      '"$request" $status $body_bytes_sent '
                      '"$http_referer" "$http_user_agent" "$http_x_forwarded_for" '
                      'rt=$request_time uct="$upstream_connect_time" uht="$upstream_header_time" urt="$upstream_response_time"';
      access_log  /var/log/nginx/access.log  main;

      sendfile on;
      tcp_nopush on;
      tcp_nodelay on;
      keepalive_timeout 65;
      types_hash_max_size 2048;
      server_tokens off;

      gzip on;
      gzip_proxied any;
      gzip_disable "msie6";
      gzip_min_length 1400;
      gzip_vary off; # Needs to be off because some files will not render properly when it's on (sets the Accept header)
      gzip_buffers 4 32k;
      gzip_types text/plain text/css image/svg+xml application/javascript application/x-javascript text/xml text/javascript application/json application/vnd.api+json;

      brotli on;
      brotli_types text/plain text/css image/svg+xml application/javascript application/x-javascript text/xml text/javascript application/json application/vnd.api+json;

      server {
          listen {{ .Values.service.internalPort }};
          keepalive_timeout 15;
          client_max_body_size 9999m;
          server_name _;

          if ($http_x_forwarded_proto = "http") {
              return 301 https://$host$request_uri;
          }

          location = /healthz {
              access_log off;
              return 200;
          }

          location = /robots.txt {
              alias /usr/share/nginx/html/robots.txt;
          }

          location / {
              # Disable caching of application requests
              add_header Cache-Control "no-cache, no-store, max-age=0, must-revalidate";
              add_header Expires "Mon, 01 Jan 1990 00:00:00 GMT";
              add_header Pragma "no-cache";

              proxy_buffering off;
              proxy_request_buffering off;
              proxy_set_header Host $host;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_pass http://127.0.0.1:{{ .Values.service.externalPort }};
          }
      }
  }
{{- end -}}
  {{- range $key, $value := .Values.configEnvs }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- range $key, $value := merge .Values.configFiles (include "wb.inlineconfigs" . | fromYaml) ((.Files.Glob "files/*").AsConfig | fromYaml) }}
  {{ $key }}: |-
    {{- $value | nindent 4 }}
  {{- end }}
