apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
        tier: frontend
    spec:
      containers:
      {{- with .Values.nginx }}
      - name: nginx
        image: "{{ .image.repository }}:{{ .image.tag }}"
        imagePullPolicy: {{ .image.pullPolicy }}
        command:
        - nginx
        - -c
        - /nginx/nginx.conf
        - -g
        - daemon off;
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /nginx
        - name: nginx-confd-config-volume
          mountPath: /etc/nginx/conf.d
        resources:
{{ toYaml .resources | indent 10 }}
      {{- end }}
      {{- with .Values.tornado }}
      - name: tornado
        image: "{{ .image.repository }}:{{ .image.tag }}"
        imagePullPolicy: {{ .image.pullPolicy }}
        command:
        - gosu
        - www-data
        - invoke
        - server
        env:
        - name: ENV
          value: kube
        ports:
        - name: http
          containerPort: 7777
        volumeMounts:
        - name: config-volume
          mountPath: /home/.cos
        - name: data-volume
          mountPath: /data
        - name: pickles-volume
          mountPath: /pickles
        resources:
{{ toYaml .resources | indent 10 }}
      {{- end }}
      {{- with .Values.celery }}
      - name: celery
        image: "{{ .image.repository }}:{{ .image.tag }}"
        imagePullPolicy: {{ .image.pullPolicy }}
        command:
        - gosu
        - www-data
        - invoke
        - celery
        env:
        - name: ENV
          value: kube
        volumeMounts:
        - name: config-volume
          mountPath: /home/.cos
        - name: data-volume
          mountPath: /data
        - name: pickles-volume
          mountPath: /pickles
        resources:
{{ toYaml .resources | indent 10 }}
      {{- end }}
      volumes:
      - name: data-volume
        emptyDir: {}
      - name: pickles-volume
        emptyDir: {}
      - name: nginx-config-volume
        configMap:
          name: {{ template "fullname" . }}
          items:
          - key: nginx.conf
            path: nginx.conf
          - key: robots.txt
            path: robots.txt
      - name: nginx-confd-config-volume
        configMap:
          name: {{ template "fullname" . }}
          items:
          - key: nginx-confd.conf
            path: default.conf
      - name: config-volume
        configMap:
          name: {{ template "fullname" . }}
          items:
          - key: settings.json
            path: waterbutler-kube.json
