apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- define "inlineconfigs" }}
preprints.conf: |-
  location ~* ^/preprints/(?!(\w+/download|\w+/\w+/download)/?$).* {
      proxy_redirect off;
      proxy_buffering off;
      proxy_pass http://{{ include "osf-ember-preprints.fullname" . }}/
  }
registries.conf: |-
  location /registries/ {
      proxy_redirect off;
      proxy_buffering off;
      proxy_pass http://{{ include "osf-ember-registries.fullname" . }}/
  }
{{- end }}
{{- range $key, $value := merge .Values.configs (merge (include "inlineconfigs" . | fromYaml) ((.Files.Glob "files/*").AsConfig | fromYaml)) }}
  {{ $key }}: |-
{{ $value | indent 4 }}
{{- end }}
