apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- define "inlineconfigs" }}
preprints.conf: |-
  location ~* ^/preprints/(?!(\w+/download|\w+/\w+/download)/?$).* {
      rewrite ^/preprints/(.*)$ /$1 break;
      proxy_redirect off;
      proxy_buffering off;
      proxy_pass http://{{ include "osf-ember-preprints.fullname" . }};
  }
registries.conf: |-
  location /registries/ {
      rewrite ^/registries/(.*)$ /$1 break;
      proxy_redirect off;
      proxy_buffering off;
      proxy_pass http://{{ include "osf-ember-registries.fullname" . }};
  }
prerender.conf: |-
{{- if .Values.prerenderHost }}
  set $prerender 0;

  if ($http_user_agent ~* "baiduspider|twitterbot|facebookexternalhit|rogerbot|linkedinbot|embedly|quora link preview|showyoubot|outbrain|pinterest|slackbot|vkShare|W3C_Validator") {
      set $prerender 1;
  }

  if ($args ~ "_escaped_fragment_") {
      set $prerender 1;
  }
  
  if ($http_user_agent ~ "Prerender") {
      set $prerender 0;
  }
  
  if ($uri ~ "\.(js|css|xml|less|png|jpg|jpeg|gif|pdf|doc|txt|ico|rss|zip|mp3|rar|exe|wmv|doc|avi|ppt|mpg|mpeg|tif|wav|mov|psd|ai|xls|mp4|m4a|swf|dat|dmg|iso|flv|m4v|torrent|ttf|woff)") {
      set $prerender 0;
  }
  
  if ($prerender = 1) {
      #setting prerender as a variable forces DNS resolution since nginx caches IPs and doesnt play well with load balancing
      set $prerender "{{ .Values.prerenderHost }}";
      rewrite .* /https://$host$request_uri? break;
      proxy_pass http://$prerender;
  }
{{- end }}
{{- end }}

{{- range $key, $value := merge .Values.configs (merge (include "inlineconfigs" . | fromYaml) ((.Files.Glob "files/*").AsConfig | fromYaml)) }}
  {{ $key }}: |-
{{ $value | indent 4 }}
{{- end }}
