apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    tier: frontend
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:

      - name: nginx
        image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
        imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
        command:
        - nginx
        - -c
        - /nginx/nginx.conf
        - -g
        - daemon off;
        ports:
        - name: http
          containerPort: {{ .Values.service.internalPort }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.internalPort }}
          initialDelaySeconds: 10
        volumeMounts:
        - mountPath: /static
          name: static-volume
        - mountPath: /nginx/nginx.conf
          name: web-config-volume
          subPath: nginx.conf
        - mountPath: /nginx/robots.txt
          name: web-config-volume
          subPath: robots.txt
        - mountPath: /etc/nginx/conf.d/default.conf
          name: web-config-volume
          subPath: nginx-confd.conf
        resources:
{{ toYaml .Values.nginx.resources | indent 10 }}

      - name: preprints
        image: "{{ .Values.preprints.image.repository }}:{{ .Values.preprints.image.tag }}"
        imagePullPolicy: {{ .Values.preprints.image.pullPolicy }}
        command:
        - sleep
        - "9999999999999999999999999999"
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -c
              - mkdir -p /static/preprints && cp -Rf /code/dist/* /static/preprints
        volumeMounts:
        - mountPath: /static
          name: static-volume
        resources:
{{ toYaml .Values.preprints.resources | indent 10 }}

      - name: registries
        image: "{{ .Values.registries.image.repository }}:{{ .Values.registries.image.tag }}"
        imagePullPolicy: {{ .Values.registries.image.pullPolicy }}
        command:
        - sleep
        - "9999999999999999999999999999"
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -c
              - mkdir -p /static/registries && cp -Rf /code/dist/* /static/registries
        volumeMounts:
        - mountPath: /static
          name: static-volume
        resources:
{{ toYaml .Values.registries.resources | indent 10 }}

      - name: uwsgi
        image: "{{ .Values.uwsgi.image.repository }}:{{ .Values.uwsgi.image.tag }}"
        imagePullPolicy: {{ .Values.uwsgi.image.pullPolicy }}
        command:
        - uwsgi
        - --ini
        - /etc/uwsgi/uwsgi.ini
        env:
        {{- include "osf.dbSettings" . | indent 8 }}
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -c
              - mkdir -p /static/code/website && cp -Rf /code/website/static /static/code/website
                && find /code/addons/ -type f | grep -i /static/ | xargs -i cp -f
                --parents {} /static/
        ports:
        - containerPort: 5000
          name: http
        - containerPort: 1717
          name: stats
        volumeMounts:
        - mountPath: /static
          name: static-volume
        - mountPath: /etc/uwsgi/uwsgi.ini
          name: web-config-volume
          subPath: uwsgi.ini
        {{- include "osf.volumeMounts" . | indent 8 }}
        resources:
{{ toYaml .Values.uwsgi.resources | indent 10 }}

      volumes:
      - name: static-volume
        emptyDir: {}
      {{- include "osf.volumes" . | indent 6 }}
