apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "nessus.fullname" . }}
  labels:
    app: {{ template "nessus.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  serviceName: {{ template "nessus.fullname" . }}
  replicas: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
        partition: 0
  template:
    metadata:
      labels:
        app: {{ template "nessus.name" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      initContainers:
        - name: bootstrap
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |-
              if [ ! -d /data/nessus ]; then
                cp -R /opt/nessus /data/nessus
              fi
          volumeMounts:
            - mountPath: /data
              name: data
      containers:
        - name: nessus
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: https
              containerPort: {{ .Values.service.internalPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
              scheme: HTTPS
          volumeMounts:
            - mountPath: /opt/nessus
              name: data
              subPath: nessus
            {{- if .Values.tls.eanbled }}
            - name: secret
              subPath: tls-servercert.pem
              mountPath: /opt/nessus/com/nessus/CA/servercert.pem
              readOnly: true
            - name: secret
              subPath: tls-serverkey.pem
              mountPath: /opt/nessus/var/nessus/CA/serverkey.pem
              readOnly: true
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        {{- if not .Values.persistence.enabled }}
        - name: data
          emptyDir: {}
        {{- end }}
        - name: secret
          secret:
            secretName: {{ template "nessus.fullname" . }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - {{ .Values.persistence.accessMode | quote }}
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
  {{- end }}
