{{- if .Values.web.horizontalPodAutoscaler.enabled -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "lookit.web.fullname" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: {{ template "lookit.web.fullname" . }}
  minReplicas: {{ .Values.web.replicaCount }}
  maxReplicas: {{ .Values.web.horizontalPodAutoscaler.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.web.horizontalPodAutoscaler.targetCPUUtilizationPercentage }}
{{- end -}}
