{{- if .Values.worker.enabled -}}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "lookit.worker.fullname" . }}
  labels:
    app: {{ template "lookit.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    component: "{{ .Values.worker.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "lookit.name" . }}
        component: "{{ .Values.worker.name }}"
        release: {{ .Release.Name }}
      annotations:
        {{- include "lookit.deploymentAnnotations" . | indent 8 }}
    spec:
      containers:
        - name: {{ .Values.worker.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - gosu
            - www-data
            - celery
            - -A
            - project.celery.app
            - worker
            - -c
            - "{{ .Values.worker.concurrency }}"
            - -l
            - INFO
            - -n
            - worker.%h
            - --without-gossip
            {{- if .Values.worker.maxTasksPerChild }}
            - --maxtasksperchild
            - "{{ .Values.worker.maxTasksPerChild }}"
            {{- end }}
            - -Q
            - "{{ .Values.worker.queues }}"
          env:
            {{- include "lookit.environment" . | indent 12 }}
          volumeMounts:
{{- if .Values.volumeMounts }}
{{ toYaml .Values.volumeMounts | indent 12 }}
{{- end }}
          resources:
{{ toYaml .Values.worker.resources | indent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "lookit.fullname" . }}
        - name: secret-volume
          secret:
            secretName: {{ template "lookit.fullname" . }}
    {{- if .Values.worker.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.worker.nodeSelector | indent 8 }}
    {{- end }}
{{- end -}}