{{- if .Values.worker.enabled -}}
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "lookit.worker.fullname" . }}
  labels:
    app: {{ template "lookit.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    component: "{{ .Values.worker.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  serviceName: {{ template "lookit.worker.fullname" . }}
  replicas: {{ .Values.worker.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "lookit.name" . }}
        component: "{{ .Values.worker.name }}"
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      containers:
        - name: docker
          image: "{{ .Values.worker.docker.image.repository }}:{{ .Values.worker.docker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.docker.image.pullPolicy }}
          args:
            - --storage-driver=overlay
          volumeMounts:
            - mountPath: /var/lib/docker
              name: docker-volume
            - mountPath: /code/ember_build/checkouts
              name: checkouts-volume
            - mountPath: /code/ember_build/deployments
              name: deployments-volume
          securityContext:
            privileged: true
          resources:
{{ toYaml .Values.worker.docker.resources | indent 12 }}
        - name: {{ .Values.worker.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - gosu
            - www-data
            - celery
            - -A
            - project.celery.app
            - worker
            - -c
            - "5"
            - -l
            - INFO
            - -n
            - worker.%h
            - --without-gossip
            - --maxtasksperchild
            - "5"
            - -Q
            - email,builds,cleanup
          env:
            - name: DOCKER_HOST
              value: 'tcp://localhost:2375'
            {{- include "lookit.environment" . | indent 12 }}
          volumeMounts:
            - mountPath: /code/ember_build/checkouts
              name: checkouts-volume
            - mountPath: /code/ember_build/deployments
              name: deployments-volume
{{- if .Values.volumeMounts }}
{{ toYaml .Values.volumeMounts | indent 12 }}
{{- end }}
          resources:
{{ toYaml .Values.worker.resources | indent 12 }}
      volumes:
        {{- if not .Values.worker.persistence.enabled }}
        - name: docker-volume
          emptyDir: {}
        {{- end }}
        - name: checkouts-volume
          emptyDir: {}
        - name: deployments-volume
          emptyDir: {}
        - name: config-volume
          configMap:
            name: {{ template "lookit.fullname" . }}
        - name: secret-volume
          secret:
            secretName: {{ template "lookit.fullname" . }}
    {{- if .Values.worker.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.worker.nodeSelector | indent 8 }}
    {{- end }}
  {{- if .Values.worker.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: docker-volume
      spec:
        accessModes:
          - {{ .Values.worker.persistence.accessMode | quote }}
      {{- if .Values.worker.persistence.storageClass }}
        storageClassName: {{ .Values.worker.persistence.storageClass | quote }}
      {{- end }}
        resources:
          requests:
            storage: {{ .Values.worker.persistence.size | quote }}
  {{- end }}
{{- end -}}
