apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        tier: frontend
    spec:
      containers:
      {{- with .Values.nginx }}
      - name: nginx
        image: "{{ .image.repository }}:{{ .image.tag }}"
        imagePullPolicy: {{ .image.pullPolicy }}
        command:
        - nginx
        - -c
        - /nginx/nginx.conf
        - -g
        - daemon off;
        resources:
{{ toYaml .resources | indent 10 }}
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /nginx
        - name: nginx-confd-config-volume
          mountPath: /etc/nginx/conf.d
      {{- end }}
      {{- with .Values.nodejs }}
      - name: nodejs
        image: "{{ .image.repository }}:{{ .image.tag }}"
        imagePullPolicy: {{ .image.pullPolicy }}
        command:
        - invoke
        args:
        - sharejs
        resources:
{{ toYaml .resources | indent 10 }}
       {{- end }}
        env:
        - name: SHAREJS_SERVER_HOST
          value: {{ .Values.serverHost }}
        - name: SHAREJS_SERVER_PORT
          value: "{{ .Values.serverPort }}"
        - name: SHAREJS_DB_NAME
          value: {{ .Values.dbName }}
        - name: SHAREJS_DB_URL
          value: "mongodb://{{ template "fullname" . }}-mongodb:27017/{{ .Values.dbName }}"
        - name: SHAREJS_CORS_ALLOW_ORIGIN
          value: {{ .Values.corsAllowOrigin }}
        - name: SHAREJS_SENTRY_DSN
          value: {{ .Values.sentryDSN }}
        ports:
        - name: http
          containerPort: 7007
      volumes:
      - name: nginx-config-volume
        configMap:
          name: {{ template "fullname" . }}
          items:
          - key: nginx.conf
            path: nginx.conf
          - key: robots.txt
            path: robots.txt
      - name: nginx-confd-config-volume
        configMap:
          name: {{ template "fullname" . }}
          items:
          - key: nginx-confd.conf
            path: default.conf
