apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sharejs.fullname" . }}
  labels:
    app: {{ template "sharejs.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
{{- define "inlineconfigs" }}
nginx.conf: |-
  user  nginx;
  worker_processes  1;

  error_log  /var/log/nginx/error.log warn;
  pid        /var/run/nginx.pid;

  events {
      worker_connections  1024;
  }

  http {
      log_format  main  '$remote_addr - $upstream_cache_status $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

      access_log  /var/log/nginx/access.log  main;

      map $http_upgrade $connection_upgrade {
          default upgrade;
          '' close;
      }

      upstream websocket {
          server 127.0.0.1:{{ .Values.service.externalPort }};
      }

      server {
          listen {{ .Values.service.internalPort }};

          location / {
              proxy_pass http://websocket;
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection $connection_upgrade;
          }
      }
  }
{{- end -}}
{{- range $key, $value := .Values.configEnvs }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- range $key, $value := merge .Values.configFiles (merge (include "inlineconfigs" . | fromYaml) ((.Files.Glob "files/*").AsConfig | fromYaml)) }}
  {{ $key }}: |-
{{ $value | indent 4 }}
{{- end }}
