apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "sharejs.fullname" . }}
  labels:
    app: {{ template "sharejs.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "sharejs.name" . }}
        release: {{ .Release.Name }}
      annotations:
        {{- include "sharejs.deploymentAnnotations" . | indent 8 }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          command:
            - nginx
            - -c
            - /etc/nginx/nginx.conf
            - -g
            - daemon off;
          ports:
            - name: http
              containerPort: {{ .Values.service.internalPort }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.internalPort }}
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: config-volume
              subPath: nginx.conf
              readOnly: true
            - mountPath: /usr/share/nginx/html/robots.txt
              name: config-volume
              subPath: robots.txt
              readOnly: true
          resources:
{{ toYaml .Values.nginx.resources | indent 12 }}
        - name: nodejs
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if .Values.mongodb.enabled }}
            - name: SHAREJS_DB_URL
              value: "mongodb://{{ include "mongodb.fullname" . }}:27017/{{ .Values.mongodb.mongodbDatabase }}"
            {{- end }}
            - name: SHAREJS_SERVER_HOST
              value: "0.0.0.0"
            - name: SHAREJS_SERVER_PORT
              value: "{{ .Values.service.externalPort }}"
            {{- include "sharejs.environment" . | indent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.service.externalPort }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.externalPort }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "sharejs.fullname" . }}
        - name: secret-volume
          secret:
            secretName: {{ template "sharejs.fullname" . }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
