{{- if and .Values.networkPolicy.enabled .Values.agent.enabled }}
kind: NetworkPolicy
apiVersion: {{ .Values.networkPolicy.apiVersion }}
metadata:
  name: {{ template "jenkins.fullname" . }}-agent
  labels:
    app: {{ template "jenkins.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    component: agent
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      # DefaultDeny
      "jenkins/{{ template "jenkins.fullname" . }}-agent": "true"
{{- end }}
