apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "cas.fullname" . }}
  labels:
    app: {{ template "cas.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "cas.name" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- if and (eq .Capabilities.KubeVersion.Major "1") (lt .Capabilities.KubeVersion.Minor "8") }}
        pod.beta.kubernetes.io/init-containers: |-
          {{- (include "cas.initContainers" . | fromYaml).initContainers | toJson | nindent 10 }}
        {{- end }}
    spec:
      affinity:
        {{- if .Values.additionalAffinities }}
        {{- toYaml .Values.additionalAffinities | nindent 8 }}
        {{- end }}
        {{- if eq .Values.antiAffinity "hard" }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: {{ template "cas.name" . }}
                  release: {{ .Release.Name }}
        {{- else if eq .Values.antiAffinity "soft" }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app: {{ template "cas.name" . }}
                    release: {{ .Release.Name }}
        {{- end }}
      {{- if or (gt .Capabilities.KubeVersion.Major "1") (and (eq .Capabilities.KubeVersion.Major "1") (ge .Capabilities.KubeVersion.Minor "8")) }}
      {{- include "cas.initContainers" . | nindent 6 }}
      {{- end }}
      containers:
        - name: apache
          image: "{{ .Values.apache.image.repository }}:{{ .Values.apache.image.tag }}"
          imagePullPolicy: {{ .Values.apache.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.internalPort }}
          livenessProbe:
            httpGet:
              httpHeaders:
                - name: Host
                  value: health
              path: /healthz
              port: {{ .Values.service.internalPort }}
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              httpHeaders:
                - name: Host
                  value: {{ .Values.casDomain }}
              path: /Shibboleth.sso/Status
              port: {{ .Values.service.internalPort }}
            initialDelaySeconds: 10
          volumeMounts:
            {{- include "cas.apache.volumeMounts" . | nindent 12 }}
        - name: jetty
          image: "{{ .Values.jetty.image.repository }}:{{ .Values.jetty.image.tag }}"
          imagePullPolicy: {{ .Values.jetty.image.pullPolicy }}
          env:
            {{- include "cas.environment" . | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.service.externalPort }}
          livenessProbe:
            httpGet:
              path: /login
              port: {{ .Values.service.externalPort }}
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /login
              port: {{ .Values.service.externalPort }}
            initialDelaySeconds: 10
          volumeMounts:
            {{- include "cas.jetty.volumeMounts" . | nindent 12 }}
      volumes:
        {{- include "cas.volumes" . | nindent 8 }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}