apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cas.fullname" . }}
  labels:
    app: {{ template "cas.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{- range $key, $value := .Values.secretEnvs }}
  {{ $key | replace "/" "-" }}: {{ $value | b64enc | quote }}
{{- end }}
{{- range $key, $value := .Values.secretFiles }}
  {{ $key | replace "/" "-" }}: {{ $value | b64enc | quote }}
{{- end }}
