# Default values for wb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: quay.io/centerforopenscience/waterbutler
  tag: develop
  pullPolicy: Always

nginx:
  image:
    repository: nginx
    tag: "1"
    pullPolicy: Always
  resources: {}
    # limits:
    #   cpu: 1
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

tornado:
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

worker:
  concurrency: 2
  logLevel: INFO
  maxTasksPerChild: 5

  resources: {}
    # limits:
    #   cpu: 2
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

horizontalPodAutoscaler:
  enabled: false
  maxReplicas: 3
  targetCPUUtilizationPercentage: 90

service:
  name: http
  type: ClusterIP
  externalPort: 7777
  internalPort: 80

ingress:
  enabled: false
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    # ingress.kubernetes.io/proxy-body-size: 9999m
    # nginx.org/client-max-body-size: 9999m
  path: /
  hosts:
  # - staging-files.osf.io
  tls:
  # - secretName: osf-io-tls
  #   hosts:
  #   - staging-files.osf.io

configEnvs: {}

configFiles: {}

secretEnvs: {}

secretFiles:
  settings.json: |-
    {
      "ANALYTICS": {
        "MFR_DOMAIN": "https://staging-mfr.osf.io",
        "KEEN": {
          "PRIVATE": {
            "PROJECT_ID": "",
            "WRITE_KEY": ""
          },
          "PUBLIC": {
            "PROJECT_ID": "",
            "WRITE_KEY": ""
          }
        }
      },
      "GITHUB_PROVIDER_CONFIG": {
        "MOVE_MESSAGE": "Moved via the Open Science Framework",
        "COPY_MESSAGE": "Copied via the Open Science Framework",
        "UPLOAD_FILE_MESSAGE": "Added via the Open Science Framework",
        "UPDATE_FILE_MESSAGE": "Updated via the Open Science Framework",
        "DELETE_FILE_MESSAGE": "Deleted via the Open Science Framework",
        "DELETE_FOLDER_MESSAGE": "Deleted via the Open Science Framework"
      },
      "OSFSTORAGE_PROVIDER_CONFIG": {
        "FILE_PATH_PENDING": "/data/pending",
        "FILE_PATH_COMPLETE": "/data/complete",
        "HMAC_SECRET": "",
        "RUN_TASKS": true
      },
      "SERVER_CONFIG": {
        "DOMAIN": "https://staging-files.osf.io",
        "ADDRESS": "0.0.0.0",
        "PORT": 7777,
        "DEBUG": false,
        "XHEADERS": true,
        "CORS_ALLOW_ORIGIN": [
          "https://staging.osf.io",
          "https://staging-mfr.osf.io"
        ],
        "HMAC_SECRET": "",
        "MAX_BUFFER_SIZE": 157286400,
        "AUTH_HANDLERS": [
          "osf"
        ]
      },
      "OSF_AUTH_CONFIG": {
        "API_URL": "https://staging.osf.io/api/v1/files/auth/",
        "JWE_SALT": "",
        "JWE_SECRET": "",
        "JWT_SECRET": ""
      },
      "TASKS_CONFIG": {
        "BROKER_URL": "amqp://guest:guest@127.0.0.1:5672//",
        "ADHOC_BACKEND_PATH": "/pickles"
      },
      "SENTRY_DSN": "",
      "LOGGING": {
        "version": 1,
        "disable_existing_loggers": false,
        "formatters": {
          "defaultFormatter": {
            "()": "waterbutler.core.logging.MaskFormatter",
            "format": "[%(asctime)s][%(levelname)s][%(name)s]: %(message)s",
            "pattern": "(?<=cookie=)(.*?)(?=&|$)",
            "mask": "***"
          }
        },
        "handlers": {
          "consoleHandler": {
            "class": "logging.StreamHandler",
            "level": "INFO",
            "formatter": "defaultFormatter"
          }
        },
        "loggers": {
          "": {
            "handlers": [
              "consoleHandler"
            ],
            "level": "INFO",
            "propagate": false
          }
        },
        "root": {
          "level": "INFO",
          "handlers": [
            "consoleHandler"
          ]
        }
      }
    }

rabbitmq:
  image:
    repository: rabbitmq
    tag: 3-management
    pullPolicy: Always

  rabbitmqUsername: guest
  rabbitmqPassword: guest
  rabbitmqNodePort: 5672
  rabbitmqNodeType: stats
  rabbitmqNodeName: rabbit@localhost
  # rabbitmqClusternodename:
  rabbitmqVhost: /
  rabbitmqManagerPort: 15672

  resources:
    requests:
      memory: 256Mi
      cpu: 100m
