dependencies:
  - name: postgresql
    version: 0.9.0
    repository: file://../postgresql
    condition: postgresql.enabled, global.postgresql.enabled
  - name: redis
    version: 1.1.2
    repository: file://../redis
    condition: redis.enabled, global.redis.enabled
