apiVersion: v1
kind: Service
metadata:
  name: {{ template "disk-usage-exporter.fullname" . }}
  labels:
    {{- include "disk-usage-exporter.labels" . | nindent 4 }}
    {{- if .Values.service.extraLabels }}
    {{- toYaml .Values.service.extraLabels | nindent 4 }}
    {{- end }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }} 
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  loadBalancerSourceRanges: {{ .Values.service.loadBalancerSourceRanges }}
  {{- end }}
  ports:
    - name: {{ .Values.service.name }}
      port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
  selector:
    app: {{ template "disk-usage-exporter.name" . }}
    release: {{ .Release.Name }}
