name: nessus
version: 0.2.0
appVersion: 6.11.2
description: Nessus Vulnerability Scanner
keywords:
- nessus
- security
home: https://www.tenable.com/products/nessus-vulnerability-scanner
icon: https://static.tenable.com/press/logos/products/Nessus-FullColor-RGB-logo.png
engine: gotpl
