# Default values for elasticsearch.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: "centerforopenscience/elasticsearch"
  tag: "5.4"
  pullPolicy: "Always"

cluster:
  name: "elasticsearch"
  config:
  env:
    # IMPORTANT: https://www.elastic.co/guide/en/elasticsearch/reference/current/important-settings.html#minimum_master_nodes
    # To prevent data loss, it is vital to configure the discovery.zen.minimum_master_nodes setting so that each master-eligible
    # node knows the minimum number of master-eligible nodes that must be visible in order to form a cluster.
    MINIMUM_MASTER_NODES: "2"

client:
  name: client
  replicas: 2
  serviceType: ClusterIP
  heapSize: "128m"
  antiAffinity: "soft"
  resources:
    limits:
      cpu: "1"
      memory: "512Mi"
    requests:
      cpu: "25m"
      memory: "256Mi"

master:
  name: master
  replicas: 3
  heapSize: "128m"
  storage: "10Gi"
  # storageClass: "ssd"
  antiAffinity: "soft"
  resources:
    limits:
      cpu: "1"
      memory: "512Mi"
    requests:
      cpu: "25m"
      memory: "256Mi"

data:
  name: data
  replicas: 2
  heapSize: "1536m"
  storage: "30Gi"
  # storageClass: "ssd"
  terminationGracePeriodSeconds: 3600
  antiAffinity: "soft"
  resources:
    limits:
      cpu: "1"
      memory: "2048Mi"
    requests:
      cpu: "25m"
      memory: "1792Mi"

## Install Default RBAC roles and bindings
rbac:
  create: false
