apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        tier: frontend
    spec:
      containers:

      - name: nginx
        image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
        imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
        command:
        - nginx
        - -c
        - /nginx/nginx.conf
        - -g
        - daemon off;
        ports:
        - containerPort: 80
          name: http
        readinessProbe:
          httpGet:
            httpHeaders:
            - name: Host
              value: status.osf.io
            path: /v2/
            port: 80
          initialDelaySeconds: 30
        volumeMounts:
        - mountPath: /static
          name: static-volume
        - mountPath: /nginx/nginx.conf
          name: api-config-volume
          subPath: nginx.conf
        - mountPath: /nginx/robots.txt
          name: api-config-volume
          subPath: robots.txt
        - mountPath: /etc/nginx/conf.d/default.conf
          name: api-config-volume
          subPath: nginx-confd.conf
        resources:
{{ toYaml .Values.nginx.resources | indent 10 }}

      - name: uwsgi
        image: "{{ .Values.uwsgi.image.repository }}:{{ .Values.uwsgi.image.tag }}"
        imagePullPolicy: {{ .Values.uwsgi.image.pullPolicy }}
        command:
        - uwsgi
        - --ini
        - /etc/uwsgi/uwsgi.ini
        env:
        {{- include "osf.dbSettings" . | indent 8 }}
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -c
              - mkdir -p /static/code/api && cp -Rf /code/api/static /static/code/api
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 1717
          name: stats
        volumeMounts:
        - mountPath: /static
          name: static-volume
        - mountPath: /etc/uwsgi/uwsgi.ini
          name: api-config-volume
          subPath: uwsgi.ini
        {{- include "osf.volumeMounts" . | indent 8 }}
        resources:
{{ toYaml .Values.uwsgi.resources | indent 10 }}

      volumes:
      - name: static-volume
        emptyDir: {}
      {{- include "osf.volumes" . | indent 6 }}