{{- if .Values.migration.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}-migration-{{ .Release.Time.Seconds }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      containers:
      - name: migrations
        image: "{{ .Values.uwsgi.image.repository }}:{{ .Values.uwsgi.image.tag }}"
        command:
        - python
        - manage.py
        - migrate
        env:
        {{- include "osf.dbSettings" . | indent 8 }}
        volumeMounts:
        - mountPath: /static
          name: static-volume
        {{- include "osf.volumeMounts" . | indent 8 }}
      volumes:
      - name: static-volume
        emptyDir: {}
      - name: config-volume
        configMap:
          name: {{ template "fullname" . }}
      {{- include "osf.volumes" . | indent 6 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
{{- end -}}
