{{- if (and .Values.api.enabled .Values.api.ingress.enabled) -}}
{{- $serviceName := include "osf.api.fullname" . }}
{{- $servicePort := .Values.api.service.externalPort -}}
{{- $ingressPaths := .Values.api.ingress.paths -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "osf.api.fullname" . }}
  labels:
    app: {{ template "osf.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    component: "{{ .Values.api.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  {{- if .Values.api.ingress.annotations }}
  annotations:
    {{- toYaml .Values.api.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  rules:
    {{- range .Values.api.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          {{- range $ingressPaths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
          {{- end -}}
    {{- end -}}
  {{- if .Values.api.ingress.tls }}
  tls:
    {{- toYaml .Values.api.ingress.tls | nindent 4 }}
  {{- end -}}
{{- end -}}
