{{- if .Values.api.enabled -}}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "osf.api.fullname" . }}
  labels:
    app: {{ template "osf.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    component: "{{ .Values.api.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "osf.name" . }}
        component: "{{ .Values.api.name }}"
        release: {{ .Release.Name }}
      annotations:
        {{- include "osf.deploymentAnnotations" . | indent 8 }}
        # Init containers not updated on upgrade : https://github.com/kubernetes/helm/issues/2702
        {{- if not .Values.collectstatic.enabled }}
        pod.beta.kubernetes.io/init-containers: |-
          [
              {
                  "name": "{{ .Values.collectstatic.name }}",
                  "image": "{{ .Values.image.repository }}:{{ .Values.image.tag }}",
                  "imagePullPolicy": "{{ .Values.image.pullPolicy }}",
                  "command": [
                      "/bin/sh",
                      "-c",
                      "mkdir -p /static/code/api && cp -Rf /code/api/static /static/code/api"
                  ],
                  "volumeMounts": [
                      {"name":"static-volume","mountPath":"/static"}
                  ]
              }
          ]
        {{- end }}
    spec:
#       {{- if not .Values.collectstatic.enabled }}
#       initContainers:
#         - name: {{ .Values.collectstatic.name }}
#           image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
#           imagePullPolicy: {{ .Values.image.pullPolicy }}
#           command:
#             - /bin/sh
#             - -c
#             - mkdir -p /static/code/api &&
#               cp -Rf /code/api/static /static/code/api
#           volumeMounts:
#             - mountPath: /static
#               name: static-volume
#       {{- end }}
      containers:
        - name: nginx
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          command:
            - nginx
            - -c
            - /nginx/nginx.conf
            - -g
            - daemon off;
          ports:
            - name: http
              containerPort: {{ .Values.api.service.internalPort }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.api.service.internalPort }}
            initialDelaySeconds: 10
          volumeMounts:
            - mountPath: /static
              name: static-volume
            - mountPath: /nginx/nginx.conf
              name: config-volume
              subPath: api-nginx.conf
              readOnly: true
            - mountPath: /nginx/robots.txt
              name: config-volume
              subPath: api-robots.txt
              readOnly: true
          resources:
{{ toYaml .Values.api.nginx.resources | indent 12 }}
        - name: {{ .Values.api.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - uwsgi
            - --ini
            - /etc/uwsgi/uwsgi.ini
            - --socket
            - :{{ .Values.api.service.externalPort }}
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: api.base.settings
            {{- include "osf.environment" . | indent 12 }}
            {{- range $key, $value := .Values.api.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            - name: wsgi
              containerPort: {{ .Values.api.service.externalPort }}
            - name: stats
              containerPort: 1717
          readinessProbe:
            tcpSocket:
              port: {{ .Values.api.service.externalPort }}
            initialDelaySeconds: 10
          volumeMounts:
            - mountPath: /etc/uwsgi/uwsgi.ini
              name: config-volume
              subPath: api-uwsgi.ini
              readOnly: true
{{- if .Values.volumeMounts }}
{{ toYaml .Values.volumeMounts | indent 12 }}
{{- end }}
          resources:
{{ toYaml .Values.api.resources | indent 12 }}
      volumes:
        - name: static-volume
          emptyDir: {}
        - name: config-volume
          configMap:
            name: {{ template "osf.fullname" . }}
        - name: secret-volume
          secret:
            secretName: {{ template "osf.fullname" . }}
    {{- if .Values.api.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.api.nodeSelector | indent 8 }}
    {{- end }}
{{- end -}}
