{{- if .Values.beat.enabled -}}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "osf.beat.fullname" . }}
  labels:
    app: {{ template "osf.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    component: "{{ .Values.beat.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "osf.name" . }}
        component: "{{ .Values.beat.name }}"
        release: {{ .Release.Name }}
      annotations:
        {{- include "osf.deploymentAnnotations" . | indent 8 }}
    spec:
      containers:
        - name: {{ .Values.beat.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - gosu
            - www-data
            - invoke
            - celery_beat
            - --schedule
            - /beat/celerybeat-schedule
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: api.base.settings
            - name: LOG_PATH
              value: /log
            {{- include "osf.environment" . | indent 12 }}
            {{- range $key, $value := .Values.beat.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          # lifecycle:
          #   postStart:
          #     exec:
          #       command:
          #         - /bin/sh
          #         - -c
          #         - chmod o+w /beat
          volumeMounts:
            - mountPath: /beat
              name: beat-volume
{{- if .Values.volumeMounts }}
{{ toYaml .Values.volumeMounts | indent 12 }}
{{- end }}
          resources:
{{ toYaml .Values.beat.resources | indent 12 }}
      volumes:
        # TODO: Remove when djang-celery-beat is configured
        - name: beat-volume
        {{- if not .Values.beat.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.beat.persistence.existingClaim | default (include "osf.beat.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: static-volume
          configMap:
            name: {{ template "osf.fullname" . }}
        - name: config-volume
          configMap:
            name: {{ template "osf.fullname" . }}
        - name: secret-volume
          secret:
            secretName: {{ template "osf.fullname" . }}
    {{- if .Values.beat.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.beat.nodeSelector | indent 8 }}
    {{- end }}
{{- end -}}
