{{- if and .Values.beat.persistence.enabled (not .Values.beat.persistence.existingClaim) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-beat
  labels:
    app: elasticsearch
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
  {{- if .Values.beat.persistence.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.beat.persistence.storageClass | quote }}
  {{- else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}
spec:
  accessModes:
    - {{ .Values.beat.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.beat.persistence.size | quote }}
{{- end -}}
