apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-flower
spec:
  replicas: {{ .Values.flower.replicaCount }}
  template:
    metadata:
      labels:
        app: flower
        tier: backend
    spec:
      containers:
      - name: celery
        image: centerforopenscience/celery-flower:latest
        imagePullPolicy: Always
        command: ["flower", "--broker", "amqp://guest:guest@rabbitmq:5672//"]
        ports:
        - name: http
          containerPort: 5555
        # resources:
        #   limits:
        #     memory: 128Mi
        #   requests:
        #     memory: 64Mi
