{{- $prefix := len .Values.ingress.domainPrefix | plural "" (print .Values.ingress.domainPrefix "-") -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
spec:
  backend:
    serviceName: {{ .Release.Name }}-osf-web
    servicePort: {{ index .Values "osf-web" "service" "externalPort" }}
  rules:
  - host: {{ if (not (empty $prefix)) }}{{ print ($prefix | trimSuffix "-") "." }}{{ end }}osf.io
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}-osf-sharejs
          servicePort: {{ index .Values "osf-sharejs" "service" "externalPort" }}
        path: /sharejs/*
  - host: {{ $prefix }}admin.osf.io
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}-osf-admin
          servicePort: {{ index .Values "osf-admin" "service" "externalPort" }}
        path: /*
  - host: {{ $prefix }}api.osf.io
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}-osf-api
          servicePort: {{ index .Values "osf-api" "service" "externalPort" }}
        path: /*
  tls:
  - hosts:
    - {{ if (not (empty $prefix)) }}{{ print ($prefix | trimSuffix "-") "." }}{{ end }}osf.io
    - {{ $prefix }}admin.osf.io
    - {{ $prefix }}api.osf.io
    secretName: osf-io-tls
