{{- if .Values.migration.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "osf.migration.fullname" . }}-{{ .Release.Time.Seconds }}
  labels:
    app: {{ template "osf.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    component: "{{ .Values.migration.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  activeDeadlineSeconds: 900
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app: {{ template "osf.name" . }}
        component: "{{ .Values.migration.name }}"
        release: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      containers:
        - name: {{ .Values.migration.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |-
              PREFIX=''
              if [ -f /code/newrelic.ini ]; then
                PREFIX='newrelic-admin run-program'
              fi
              $PREFIX python manage.py migrate
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: api.base.settings
            {{- include "osf.environment" . | indent 12 }}
            {{- range $key, $value := .Values.migration.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
{{- if or .Values.volumeMounts .Values.migration.volumeMounts }}
          volumeMounts:
{{ toYaml .Values.volumeMounts | indent 12 }}
{{- if .Values.migration.volumeMounts }}
{{ toYaml .Values.migration.volumeMounts | indent 12 }}
{{- end }}
{{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "osf.fullname" . }}
        - name: secret-volume
          secret:
            secretName: {{ template "osf.fullname" . }}
    {{- if .Values.migration.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.migration.nodeSelector | indent 8 }}
    {{- end }}
{{- end -}}
