apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  sensitive-data-salt: {{ .Values.osf.salt | b64enc }}
  sensitive-data-secret: {{ .Values.osf.secret | b64enc }}
