{{- if (and .Values.web.enabled .Values.web.ingress.enabled) -}}
{{- $ingressPaths := .Values.web.ingress.paths -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "osf.web.fullname" . }}
  labels:
    app: {{ template "osf.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    component: "{{ .Values.web.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  {{- if .Values.web.ingress.annotations }}
  annotations:
    {{- toYaml .Values.web.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  rules:
    {{- if .Values.maintenance.enabled }}
    {{- $serviceName := include "maintenance.fullname" . -}}
    {{- $servicePort := .Values.maintenance.service.externalPort -}}
    {{- range .Values.api.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          {{- range $ingressPaths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
          {{- end -}}
    {{- end -}}
    {{- else -}}
    {{- $shareJSEnabled := .Values.sharejs.enabled -}}
    {{- $shareJSServiceName := .Values.sharejs.service.name -}}
    {{- $shareJSServicePort := .Values.sharejs.service.externalPort -}}
    {{- $shareJSIngressPaths := .Values.sharejs.ingress.paths -}}
    {{- $serviceName := include "osf.web.fullname" . -}}
    {{- $servicePort := .Values.web.service.externalPort -}}
    {{- range .Values.web.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          {{- if $shareJSEnabled }}
          {{- range $shareJSIngressPaths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $shareJSServiceName }}
              servicePort: {{ $shareJSServicePort }}
          {{- end }}
          {{- end }}
          {{- range $ingressPaths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
          {{- end }}
    {{- end -}}
    {{- end -}}
  {{- if .Values.web.ingress.tls }}
  tls:
    {{- toYaml .Values.web.ingress.tls | nindent 4 }}
  {{- end -}}
{{- end -}}
