{{- if .Values.worker.enabled -}}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "osf.worker.fullname" . }}
  labels:
    app: {{ template "osf.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    component: "{{ .Values.worker.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "osf.name" . }}
        component: "{{ .Values.worker.name }}"
        release: {{ .Release.Name }}
      annotations:
        {{- include "osf.deploymentAnnotations" . | indent 8 }}
    spec:
      containers:
        - name: {{ .Values.worker.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - gosu
            - www-data
            - invoke
            - celery_worker
            - --hostname
            - worker.%h
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: api.base.settings
            {{- include "osf.environment" . | indent 12 }}
            {{- range $key, $value := .Values.worker.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
{{- if .Values.volumeMounts }}
{{ toYaml .Values.volumeMounts | indent 12 }}
{{- end }}
          resources:
{{ toYaml .Values.worker.resources | indent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "osf.fullname" . }}
        - name: secret-volume
          secret:
            secretName: {{ template "osf.fullname" . }}
    {{- if .Values.worker.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.worker.nodeSelector | indent 8 }}
    {{- end }}
{{- end -}}
