apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "elasticsearch.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.client.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "elasticsearch.client.fullname" . }}
  {{- if .Values.client.service.annotations }}
  annotations:
    {{- toYaml .Values.client.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.client.service.type }}
  {{- if and (eq .Values.client.service.type "LoadBalancer") .Values.client.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.client.service.loadBalancerIP | quote }}
  {{- end }}
  ports:
    - port: 9200
      targetPort: http
  {{- if .Values.client.service.externalIPs }}
  externalIPs:
    {{- toYaml .Values.client.service.externalIPs | nindent 4 }}
  {{- end }}
  selector:
    app: {{ template "elasticsearch.name" . }}
    component: "{{ .Values.client.name }}"
    release: {{ .Release.Name }}
