apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    app: {{ template "elasticsearch.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.master.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "elasticsearch.master.fullname" . }}
spec:
  serviceName: {{ template "elasticsearch.master.fullname" . }}
  replicas: {{ .Values.master.replicas }}
  {{- if .Values.master.updateStrategy }}
  updateStrategy:
    {{- toYaml .Values.master.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ template "elasticsearch.name" . }}
        component: "{{ .Values.master.name }}"
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "elasticsearch.fullname" . }}
      affinity:
        {{- if .Values.master.additionalAffinities }}
        {{- toYaml .Values.master.additionalAffinities | nindent 8 }}
        {{- end }}
        {{- if eq .Values.master.antiAffinity "hard" }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app: "{{ template "elasticsearch.name" . }}"
                  release: "{{ .Release.Name }}"
                  component: "{{ .Values.master.name }}"
        {{- else if eq .Values.master.antiAffinity "soft" }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app: "{{ template "elasticsearch.name" . }}"
                    release: "{{ .Release.Name }}"
                    component: "{{ .Values.master.name }}"
        {{- end }}
      initContainers:
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html
      # and https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration-memory.html#mlockall
      - name: "sysctl"
        image: "busybox"
        imagePullPolicy: "Always"
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: "chown"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ default "" .Values.image.pullPolicy | quote }}
        command:
        - /bin/bash
        - -c
        - chown -R elasticsearch:elasticsearch /usr/share/elasticsearch/data &&
          chown -R elasticsearch:elasticsearch /usr/share/elasticsearch/logs
        securityContext:
          runAsUser: 0
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: data
      containers:
      - name: elasticsearch
        env:
        - name: SERVICE
          value: {{ template "elasticsearch.master.fullname" . }}
        - name: KUBERNETES_MASTER
          value: kubernetes.default.svc.cluster.local
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_DATA
          value: "false"
{{- if hasPrefix "5." .Values.image.tag }}
        - name: NODE_INGEST
          value: "false"
{{- end }}
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        - name: ES_JAVA_OPTS
          value: "-Djava.net.preferIPv4Stack=true -Xms{{ .Values.master.heapSize }} -Xmx{{ .Values.master.heapSize }}"
        {{- range $key, $value :=  .Values.cluster.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        resources:
          {{- toYaml .Values.master.resources | nindent 12 }}
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - curl
                --request GET
                --silent
                --output /dev/null
                {{- if .Values.tls.enabled }}
                --insecure
                --crlfile /usr/share/elasticsearch/config/ca_crl.pem
                --key /usr/share/elasticsearch/config/server_key.pem
                --cacert /usr/share/elasticsearch/config/ca_cert.pem
                --cert /usr/share/elasticsearch/config/server_cert.pem
                https://127.0.0.1:9200/_cluster/health?local=true
                {{- else }}
                http://127.0.0.1:9200/_cluster/health?local=true
                {{- end }}
          initialDelaySeconds: 5
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ default "" .Values.image.pullPolicy | quote }}
        ports:
        - containerPort: 9300
          name: transport
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: data
        - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          name: config
          subPath: elasticsearch.yml
          readOnly: true
{{- if hasPrefix "2." .Values.image.tag }}
        - mountPath: /usr/share/elasticsearch/config/logging.yml
          name: config
          subPath: logging.yml
          readOnly: true
{{- end }}
{{- if hasPrefix "5." .Values.image.tag }}
        - mountPath: /usr/share/elasticsearch/config/log4j2.properties
          name: config
          subPath: log4j2.properties
          readOnly: true
{{- end }}
        {{- if .Values.tls.enabled }}
        - mountPath: /usr/share/elasticsearch/config/server_cert.pem
          name: secret
          subPath: server_cert.pem
          readOnly: true
        - mountPath: /usr/share/elasticsearch/config/server_key.pem
          name: secret
          subPath: server_key.pem
          readOnly: true
        - mountPath: /usr/share/elasticsearch/config/ca_cert.pem
          name: secret
          subPath: ca_cert.pem
          readOnly: true
        - mountPath: /usr/share/elasticsearch/config/ca_crl.pem
          name: secret
          subPath: ca_crl.pem
          readOnly: true
        {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ template "elasticsearch.fullname" . }}
      {{- if not .Values.master.persistence.enabled }}
      - name: data
        emptyDir: {}
      {{- end }}
      {{- if .Values.tls.enabled }}
      - name: secret
        secret:
          secretName: {{ template "elasticsearch.fullname" . }}
      {{- end }}
  {{- if .Values.master.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - {{ .Values.master.persistence.accessMode | quote }}
      {{- if hasKey .Values.master.persistence "storageClass" }}
        storageClassName: {{ .Values.master.persistence.storageClass | quote }}
      {{- end }}
        resources:
          requests:
            storage: {{ .Values.master.persistence.size | quote }}
  {{- end }}
