apiVersion: v1
kind: Secret
metadata:
  name: {{ template "postgresql.fullname" . }}
  labels:
    app: {{ template "postgresql.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{- define "inlinesecrets" }}
{{- $master_host := or .Values.secrets.MASTER_HOST (cat (include "postgresql.fullname" .) "-0") -}}
barman-db.conf: |-
  ; Barman, Backup and Recovery Manager for PostgreSQL
  ; http://www.pgbarman.org/ - http://www.2ndQuadrant.com/
  ;
  ; Template configuration file for a server using
  ; only streaming replication protocol
  ;

  [{{ .Values.secrets.POSTGRES_DB }}]
  ; Human readable description
  description =  "{{ .Values.secrets.POSTGRES_DB }} Database (Streaming)"

  ; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  ; PostgreSQL connection string (mandatory)
  ; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  conninfo = host={{ $master_host }} user=barman dbname={{ .Values.secrets.POSTGRES_DB }} password={{ .Values.secrets.BARMAN_PASSWORD }}
  ; future, backup from replica {{ template "postgresql.fullname" . }}-1

  ; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  ; PostgreSQL streaming connection string
  ; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  ; To be used by pg_basebackup for backup and pg_receivexlog for WAL streaming
  ; NOTE: streaming_barman is a regular user with REPLICATION privilege
  streaming_conninfo = host={{ $master_host }} user=barman_streaming password={{ .Values.secrets.BARMAN_STREAMING_PASSWORD }}

  ; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  ; Backup settings (via pg_basebackup)
  ; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  backup_method = postgres
  ;streaming_backup_name = barman_streaming_backup

  ; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  ; WAL streaming settings (via pg_receivexlog)
  ; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  streaming_archiver = on
  slot_name = barman
  ;streaming_archiver_name = barman_receive_wal
  ;streaming_archiver_batch_size = 50

  ; PATH setting for this server
  ;path_prefix = "/usr/pgsql-9.6/bin"

  retention_policy = REDUNDANCY 3
{{- end -}}
  {{- if .Values.metrics.customMetrics }}
  custom-metrics.yaml: {{ toYaml .Values.metrics.customMetrics | b64enc | quote }}
  {{- end }}
{{- range $key, $value := merge .Values.secrets (include "inlinesecrets" . | fromYaml) }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}