apiVersion: v1
kind: Service
metadata:
  name: {{ template "postgresql.standby.fullname" . }}
  labels:
    app: {{ template "postgresql.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    component: "{{ .Values.standby.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Values.metrics.enabled }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: postgresql
      port: {{ .Values.service.port }}
      targetPort: postgresql
{{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
  selector:
    app: {{ template "postgresql.name" . }}
    component: "{{ .Values.standby.name }}"
    release: {{ .Release.Name }}
