apiVersion: v1
kind: Service
metadata:
  name: {{ template "postgresql.standby.fullname" . }}
  labels:
    app: {{ template "postgresql.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    component: "{{ .Values.standby.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if or .Values.standby.service.annotations .Values.metrics.enabled }}
  annotations:
  {{- if .Values.standby.service.annotations }}
{{ toYaml .Values.standby.service.annotations | indent 4 }}
  {{- end }}
  {{- if .Values.metrics.enabled }}
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
  {{- end }}
{{- end }}
spec:
  type: {{ .Values.standby.service.type }}
  {{- if and (eq .Values.standby.service.type "LoadBalancer") .Values.standby.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.standby.service.loadBalancerIP | quote }}
  {{- end }}
  ports:
    - name: postgresql
      port: {{ .Values.standby.service.port }}
      targetPort: postgresql
{{- if .Values.standby.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.standby.service.externalIPs | indent 4 }}
{{- end }}
  selector:
    app: {{ template "postgresql.name" . }}
    component: "{{ .Values.standby.name }}"
    release: {{ .Release.Name }}
