apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rabbitmq.fullname" . }}
  labels:
    app: {{ template "rabbitmq.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  password: {{ .Values.password | default (randAlphaNum 10) | b64enc | quote }}
  erlangCookie: {{ .Values.erlangCookie | default (randAlphaNum 32) | b64enc | quote }}
