# Default values for lookit.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: quay.io/centerforopenscience/lookit
  tag: develop
  pullPolicy: Always

web:
  enabled: true
  name: web
  replicaCount: 1

  nginx:
    image:
      repository: nginx
      tag: "1"
      pullPolicy: Always
    resources: {}
      # We usually recommend not to specify default resources and to leave this as a conscious
      # choice for the user. This also increases chances charts run on environments with little
      # resources, such as Minikube. If you do want to specify resources, uncomment the following
      # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
      #limits:
      #  cpu: "1"
      #  memory: 128Mi
      #requests:
      #  cpu: 100m
      #  memory: 128Mi

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    #limits:
    #  cpu: 100m
    #  memory: 128Mi
    #requests:
    #  cpu: 100m
    #  memory: 128Mi

  service:
    name: http
    type: ClusterIP
    externalPort: 5000
    internalPort: 80

worker:
  enabled: true
  name: worker
  replicaCount: 1

  docker:
    image:
      repository: docker
      tag: 17.06-dind
      pullPolicy: Always
    resources: {}
      # We usually recommend not to specify default resources and to leave this as a conscious
      # choice for the user. This also increases chances charts run on environments with little
      # resources, such as Minikube. If you do want to specify resources, uncomment the following
      # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
      #limits:
      #  cpu: "1"
      #  memory: 512Mi
      #requests:
      #  cpu: 100m
      #  memory: 256Mi

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    #limits:
    #  cpu: 100m
    #  memory: 128Mi
    #requests:
    #  cpu: 100m
    #  memory: 128Mi

collectstatic:
  enabled: false
  name: collectstatic

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    #limits:
    #  cpu: 100m
    #  memory: 128Mi
    #requests:
    #  cpu: 100m
    #  memory: 128Mi

migration:
  enabled: true
  name: migration

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    #limits:
    #  cpu: 100m
    #  memory: 128Mi
    #requests:
    #  cpu: 100m
    #  memory: 128Mi

ingress:
  enabled: false
  # Used to create Ingress record (should used with service.type: ClusterIP).
  hosts:
    - chart-example.local
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  tls:
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local

configEnvs:
  DEBUG: ""
  DJANGO_SETTINGS_MODULE: project.settings
  GEVENT: "1"
  ALLOWED_HOSTS: "*"
  # GOOGLE_APPLICATION_CREDENTIALS: /etc/googleAppCreds.json
  # MEDIA_URL: https://storage.googleapis.com/bucket/media/
  # STATIC_URL: https://storage.googleapis.com/bucket/static/
  # GS_BUCKET_NAME: "bucket"
  # GS_PROJECT_ID: "project-id"
  # EMAIL_HOST: ""
  # EMAIL_PORT: 587
  # EMAIL_USE_TLS: "True"
  # EMAIL_FROM_ADDRESS: ""
  # LOGIN_REDIRECT_URL: https://chart-example.local/exp/
  # SITE_DOMAIN: chart-example.local
  # ACCOUNT_LOGOUT_REDIRECT_URL: /login/
  # AWS_DEFAULT_REGION: "us-east-1"
  # BUCKET_NAME: ""

configFiles: {}
  # Override configmap files here (and delete the {} above), e.g.:
  #robots.txt: |-
  #  User-agent: *
  #  Disallow: /

secretEnvs: {}
  # AWS_ACCESS_KEY_ID: "abc123"
  # AWS_SECRET_ACCESS_KEY: ""
  # EMAIL_HOST_USER: ""
  # EMAIL_HOST_PASSWORD: ""
  # RAVEN_DSN: ""

secretFiles: {}
  # googleAppCreds.json: |-
  #   ...

# volumeMounts:
#   - mountPath: /code/project/settings/local.py
#     name: secret-volume
#     subPath: local.py
#     readOnly: true
#   - mountPath: /etc/googleAppCreds.json
#     name: secret-volume
#     subPath: googleAppCreds.json
#     readOnly: true

postgresql:
  image: "postgres"
  imageTag: "9.6"

  ## Specify a imagePullPolicy
  ## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  # imagePullPolicy:

  ## Create a database user
  ## Default: postgres
  postgresUser: postgres

  ## Password for the new user.
  ## Default: If not set, a random 10 characters password will be used.
  postgresPassword: lookit

  ## Create a database
  ## Default: the postgres user
  postgresDatabase: lookit

  # Specify initdb arguments, e.g. --data-checksums
  # ref: https://github.com/docker-library/docs/blob/master/postgres/content.md#postgres_initdb_args
  # ref: https://www.postgresql.org/docs/current/static/app-initdb.html
  postgresInitdbArgs: --data-checksums

  ## Persist data to a persitent volume
  persistence:
    enabled: true

    ## A manually managed Persistent Volume and Claim
    ## Requires persistence.enabled: true
    ## If defined, PVC must be created manually before volume will be bound
    # existingClaim:

    ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
    ## Default: volume.alpha.kubernetes.io/storage-class: default
    ##
    # storageClass: ssd
    accessMode: ReadWriteOnce
    size: 25Gi
    subPath: "postgresql-db"

  metrics:
    enabled: false

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    #limits:
    #  cpu: "1"
    #  memory: 256Mi
    #requests:
    #  cpu: 100m
    #  memory: 256Mi
