dependencies:
  - name: elasticsearch
    version: 0.1.10
    repository: file://../elasticsearch
    condition: elasticsearch.enabled, global.elasticsearch.enabled
  - name: maintenance
    version: 0.1.0
    repository: file://../maintenance
    condition: maintenance.enabled, global.maintenance.enabled
  - name: postgresql
    version: 0.8.1
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: postgresql.enabled, global.postgresql.enabled
  - name: rabbitmq
    version: 0.6.8
    repository: file://../rabbitmq
    condition: rabbitmq.enabled, global.rabbitmq.enabled
  - name: redis
    version: 1.1.2
    repository: file://../redis
    condition: redis.enabled, global.redis.enabled