dependencies:
  - name: elasticsearch
    version: 0.1.10
    repository: file://../elasticsearch
    condition: elasticsearch.enabled, global.elasticsearch.enabled
  - name: postgresql
    version: 0.8.1
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: postgresql.enabled, global.postgresql.enabled
  - name: rabbitmq
    version: 0.6.3
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: rabbitmq.enabled, global.rabbitmq.enabled
  - name: prerender
    version: 0.1.0
    repository: file://../prerender
    condition: prerender.enabled, global.prerender.enabled
  - name: osf-preprints
    version: 0.1.0
    repository: file://../osf-preprints
    condition: osf-preprints.enabled, global.osf-preprints.enabled
  - name: osf-registries
    version: 0.1.0
    repository: file://../osf-registries
    condition: osf-registries.enabled, global.osf-registries.enabled
