{{- if .Values.controller.budget.minAvailable -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: "{{ template "controller.fullname" . }}"
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.controller.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ template "name" . }}
      component: "{{ .Values.controller.name }}"
      release: {{ .Release.Name }}
  minAvailable: {{ .Values.controller.budget.minAvailable }}
{{- end -}}
