apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "barman.fullname" . }}
  labels:
    app: {{ template "barman.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
{{- define "inlineconfigs" }}
cron.d-barman_schedule: |-
  # /etc/cron.d/barman_schedule: crontab entries for barman
  {{- range $key, $value := .Values.backups }}
  {{ $value.schedule }} barman /usr/bin/barman backup {{ $key }}
  {{- end }}
{{- end -}}
{{- range $key, $value := merge .Values.configFiles (merge (include "inlineconfigs" . | fromYaml) ((.Files.Glob "files/*").AsConfig | fromYaml)) }}
  {{ $key }}: |-
{{ $value | indent 4 }}
{{- end }}
