apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "stats-daemon.fullname" . }}
  labels:
    app: {{ template "stats-daemon.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  {{- range $key, $value := .Values.configEnvs }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- range $key, $value := merge .Values.configFiles }}
  {{ $key }}: |-
    {{- $value | nindent 4 }}
  {{- end }}